### ISSUE TITLE
Symstore add doesn't seems to care about previous transactions

### ISSUE THREAD

**Issue by mihaipopescu** [elmirjagudin/symstore#12]
I would expect that when I'm doing another `add`, `symstore` would know that files with the same checksums were already added in previous transactions and only add the ones that are actually changed. It seems all files are always added to the transaction file even though the update was not really necessary as the file was previously known in the transaction files (I'm not necessarily talking about OS file system level which should not matter).

**Comment by elmirjagudin** [comment]
If you mean the transaction list files in '000Admin', the 000Admin/0000000XXX file, then it's true. Symstore does not take into account any previous transactions, it will list all file specified with the 'add' command.

This is the expected behavior. I checked what the miscrosoft's symstore.exe does, and it behaves in the same way.

Does that cause any problems for you?

**Comment by mihaipopescu** [comment]
No, not necessarily. I just thought it's the reason it existed. Thanks for checking this out and thanks for the package.
